FROM node:20-alpine

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json ./
COPY pnpm-lock.yaml* ./ 

RUN pnpm install

COPY . .

CMD ["pnpm", "run", "dev"]