services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: vorlaxen_bot
    restart: unless-stopped
    environment:
      NODE_ENV: production
    volumes:
      - ./media:/app/media
    networks:
      - coolify

networks:
  coolify:
    external: true