FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

RUN find src/modules -type d \( -name "commands" -o -name "events" \) | while read -r dir; do \
    dest="/app/${dir}"; \
    mkdir -p "$dest"; \
    cp -rf "$dir/." "$dest/"; \
    done

FROM node:20-alpine AS runner
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

ENV NODE_ENV=production

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/modules ./src/modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --prod --frozen-lockfile

RUN mkdir -p logs media data

EXPOSE 5000

CMD ["node", "-r", "module-alias/register", "dist/app.js"]